test:
  adapter: postgresql
  encoding: unicode
  database: digiwings_test
  pool: 5
  username: digiwings
  password: password

development:
  adapter: postgresql
  encoding: unicode
  database: digiwings_development
  pool: 5
  username: digiwings
  password: password

